{
 "title": "DNS Request Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "kindling_entity_request_duration_nanoseconds_count{protocol=\"dns\"}"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "kindling_entity_request_duration_nanoseconds_count{namespace =\"$namespace\", protocol=\"dns\"} "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dst_ip) (increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\",src_workload_name=\"$workload\", protocol=\"dns\"}[$__interval]))",
     "legendFormat": "{{ dst_ip }}"
    }
   ]
  },
  {
   "title": "Status Error Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dst_ip) (increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\", status_code!=\"0\"}[$__interval]))",
     "legendFormat": "{{dst_ip}}"
    }
   ]
  },
  {
   "title": "Response Timeout Counts",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(kindling_topology_request_duration_nanoseconds_bucket{src_namespace=\"$namespace\",src_workload_name=\"$workload\",le=\"+Inf\"}[$__interval])) - sum(increase(kindling_topology_request_duration_nanoseconds_bucket{src_namespace=\"$namespace\",src_workload_name=\"$workload\",le=\"5e+08\"}[$__interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Parsing Domain Failure Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\", status_code!=\"0\"}[$__interval])) by (dst_ip))",
     "legendFormat": "{{ dst_ip }}"
    }
   ]
  },
  {
   "title": "All Request Failure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(sum(increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\", status_code!=\"0\"}[$__interval])) by (status_code), \"status_code\", \"FormatErr\", \"status_code\", \"1.*\"), \"status_code\", \"ServFail\", \"status_code\", \"2.*\"), \"status_code\", \"NXDomain\", \"status_code\", \"3.*\"), \"status_code\", \"NotImp\", \"status_code\", \"4.*\"), \"status_code\", \"Refused\", \"status_code\", \"5.*\")",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_topology_request_duration_nanoseconds_sum{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (dst_ip) /\nsum(increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (dst_ip)",
     "legendFormat": "{{dst_ip}}"
    }
   ]
  },
  {
   "title": "DNS Request Detail",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kindling_trace_request_duration_nanoseconds{src_namespace=\"$namespace\", src_workload_name=\"$workload\", protocol=\"dns\"}"
    }
   ]
  }
 ]
}