// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: subscribe.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubEvent struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pid                  uint32   `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Labels               []*Label `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubEvent) Reset()         { *m = SubEvent{} }
func (m *SubEvent) String() string { return proto.CompactTextString(m) }
func (*SubEvent) ProtoMessage()    {}
func (*SubEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d2980c9543da44, []int{0}
}
func (m *SubEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubEvent.Unmarshal(m, b)
}
func (m *SubEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubEvent.Marshal(b, m, deterministic)
}
func (m *SubEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubEvent.Merge(m, src)
}
func (m *SubEvent) XXX_Size() int {
	return xxx_messageInfo_SubEvent.Size(m)
}
func (m *SubEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SubEvent proto.InternalMessageInfo

func (m *SubEvent) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SubEvent) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SubEvent) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Label struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d2980c9543da44, []int{1}
}
func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SubEvent)(nil), "model.SubEvent")
	proto.RegisterType((*Label)(nil), "model.Label")
}

func init() { proto.RegisterFile("subscribe.proto", fileDescriptor_38d2980c9543da44) }

var fileDescriptor_38d2980c9543da44 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x4d, 0x2a,
	0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f,
	0x49, 0xcd, 0x51, 0x8a, 0xe1, 0xe2, 0x08, 0x2e, 0x4d, 0x72, 0x2d, 0x4b, 0xcd, 0x2b, 0x11, 0x92,
	0xe0, 0x62, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x82, 0x71, 0x85, 0x04, 0xb8, 0x98, 0x0b, 0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83,
	0x40, 0x4c, 0x21, 0x15, 0x2e, 0xb6, 0x9c, 0xc4, 0xa4, 0xd4, 0x9c, 0x62, 0x09, 0x16, 0x05, 0x66,
	0x0d, 0x6e, 0x23, 0x1e, 0x3d, 0xb0, 0x79, 0x7a, 0x3e, 0x20, 0xc1, 0x20, 0xa8, 0x9c, 0x92, 0x39,
	0x17, 0x2b, 0x58, 0x40, 0x48, 0x8a, 0x8b, 0x23, 0x39, 0xb1, 0x24, 0x35, 0x3d, 0xbf, 0xa8, 0x12,
	0x6c, 0x36, 0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x0a, 0x36, 0x9d,
	0x33, 0x08, 0xcc, 0x76, 0x12, 0x8c, 0xe2, 0x07, 0x9b, 0xa7, 0x0f, 0x77, 0x76, 0x12, 0x1b, 0xd8,
	0xdd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x42, 0xae, 0x26, 0xca, 0x00, 0x00, 0x00,
}
