{
 "title": "DNS Request Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "kindling_entity_request_duration_nanoseconds_count{protocol=\"dns\"}"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "kindling_entity_request_duration_nanoseconds_count{namespace =\"$namespace\", protocol=\"dns\"} "
   }
  ]
 },
 "panels": [
  {
   "title": "Request Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_topology_request_duration_nanoseconds_count{src_namespace=\"$namespace\",src_workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (src_workload_name)",
     "legendFormat": "{{src_workload_name}}"
    }
   ]
  },
  {
   "title": "Response Timeout Counts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kindling_entity_request_duration_nanoseconds_count{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\", response_content!=\"0\"}[$__interval])) by (pod)",
     "legendFormat": "{{request_content}}"
    }
   ]
  },
  {
   "title": "All Request Failure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kindling_entity_request_duration_nanoseconds_count{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\", response_content!=\"0\"}[$__interval])) by (response_content)",
     "legendFormat": "{{response_content}}"
    }
   ]
  },
  {
   "title": "Parsing Domain Failure Top10",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(kindling_entity_request_duration_nanoseconds_count{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\", response_content!=\"0\"}[$__interval])) by (request_content))",
     "legendFormat": "{{ request_content }}"
    }
   ]
  },
  {
   "title": "Response Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_entity_request_duration_nanoseconds_count{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (namespace, workload_name)",
     "legendFormat": "{{workload_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kindling_entity_request_duration_nanoseconds_sum{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (namespace, workload_name) /\nsum(increase(kindling_entity_request_duration_nanoseconds_count{namespace=\"$namespace\", workload_name=\"$workload\", protocol=\"dns\"}[$__interval])) by (namespace, workload_name)",
     "legendFormat": "{{workload_name}}"
    }
   ]
  },
  {
   "title": "DNS Timeout Request Detail",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kindling_trace_request_duration_nanoseconds{dst_namespace=\"$namespace\", dst_workload_name=\"$workload\", protocol=\"dns\"}"
    }
   ]
  }
 ]
}