FROM golang:1.20.2-bullseye AS builder
WORKDIR /build

ENV GOPROXY https://goproxy.cn
COPY go11.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o metadata-provider ./cmd/metadata-provider

FROM debian:bullseye-slim AS runner
WORKDIR /app
COPY --from=builder /build/metadata-provider /app/
CMD ["/app/metadata-provider"]